# FROM cjrada/python-azureiot-arm32v7:latest
FROM cjrada/python-azureiot-gopigo3-arm32v7:latest

# WORKDIR /app

# COPY requirements.txt ./
# RUN pip install -r requirements.txt

COPY ./modules/GoPiGoController ./

CMD [ "python3", "-u", "./main.py" ]
